version: '3'

includes:
  app: 
    taskfile: ./common/Taskfile.yml
    optional: true
  sub: 
    taskfile: ./common/tasks/sub-Taskfile.yml
    optional: true
  ci: 
    taskfile: ./common/tasks/ci-Taskfile.yml
    optional: true

tasks:
  init:
    desc: "Initialize repository"
    cmds: 
      - git submodule init
      - git submodule update --remote --checkout
      - npm install
      - cd common && git checkout BAK-559 && cd ..
      - lefthook add commit-msg
      - lefthook add pre-commit
